Traceback (most recent call last):
  File "/usr/bin//cutadapt", line 11, in <module>
    load_entry_point('cutadapt==1.15', 'console_scripts', 'cutadapt')()
  File "/usr/lib/python3/dist-packages/cutadapt/__main__.py", line 688, in main
    pipeline = pipeline_from_parsed_args(options, paired, pair_filter_mode, quality_filename, is_interleaved_output)
  File "/usr/lib/python3/dist-packages/cutadapt/__main__.py", line 577, in pipeline_from_parsed_args
    adapters = adapter_parser.parse_multi(options.adapters, options.anywhere, options.front)
  File "/usr/lib/python3/dist-packages/cutadapt/adapters.py", line 194, in parse_multi
    adapters.extend(self.parse(spec, cmdline_type))
  File "/usr/lib/python3/dist-packages/cutadapt/adapters.py", line 163, in parse
    for record in fasta:
  File "/usr/lib/python3/dist-packages/cutadapt/seqio.py", line 232, in __iter__
    "FASTA record, but got {1!r}.".format(i+1, _shorten(line)))
cutadapt.seqio.FormatError: At line 1: Expected '>' at beginning of FASTA record, but got 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'.
